### ISSUE TITLE
Possible wrong knight move rule

### ISSUE THREAD

**Issue by stas730** [paladin8/kfchess#5]
From kfchess/ui/util/GameLogic.js:
`function isKnightLegalMove(game, currentTick, piece, toRow, toCol) {
    const rowDelta = Math.abs(toRow - piece.row), colDelta = Math.abs(toCol - piece.col);
    if (!((rowDelta === 1 && colDelta === 2) || (rowDelta === 2 && colDelta === 1))) {
        return false;
}`
I haven’t learned JS, but this looks like wrong rule:

>  The knight move is unusual among chess pieces. It moves to a square that is two squares away horizontally and one square vertically, or two squares vertically and one square horizontally.
[Source: Wikipedia]

The real rule is:

> 3.6 The knight may move to one of the squares nearest to that on which it stands but not on the same rank, file or diagonal.
[Source: FIDE Laws of Chess]

**Comment by paladin8** [comment]
I'm fairly sure those are equivalent. Do you have a case in which you think they would differ?

**Comment by stas730** [comment]
Different code is executed, so different task is done.

**Comment by paladin8** [comment]
I can't think of any case where they differ, so closing this out.
