### ISSUE TITLE
Sumo Volleyball ?

### ISSUE THREAD

**Issue by Infamous2017** [paladin8/kfchess#6]
Hey, You have Sumo Volleyball Open Source too?  ICQ Sumo Volleyball or Shizmoo Sumo Volleyball? I AM MISSING IT

**Comment by paladin8** [comment]
I miss Sumo Volleyball as well! Unfortunately, I don't have time to re-build it, but perhaps in the future...

**Comment by chenarviv** [comment]
Hey, do you want to collaborate to bring up Sumo volleyball?

**Comment by paladin8** [comment]
@chenarviv Unfortunately, I don't have time in the foreseeable future to work on it.

**Comment by chenarviv** [comment]
@paladin8 I see, do you have any idea which technology was used to develop this game? And do you know any pieces of source code?
